### ISSUE TITLE
Other links

### ISSUE THREAD

**Issue by franciscop-invast** [muhajirframe/is-internal-link#3]
Hey thanks for the project, looks very nice. There are other possibilities that are internal but would not be matched with the current Regex, like those:

```html
<a href="hello">
<a href="hello.html">
<a href="./hello">
<a href="../hello">
<a href="https-is-better-than-http.html">
```

I would suggest going the other route and instead checking if it's not external since it's normally easier:

```js
// External links regexp, they start by one of those: 'http://', 'https://', '//'
const external = /^(https?:\/\/|\/\/)/i;

export const isInternalLink = (link: string) => !external.test(link);
```

**Comment by franciscop-invast** [comment]
Here are the tests for this Regex: https://regex101.com/r/k71umu/1

**Comment by muhajirdev** [comment]
Woah, awesome insight. Do you want to make a Pull Request for this? If you do, make a `Contributor` section in README.md . And put your username there 👍 .

And btw, how did you get to this repo?

**Comment by franciscop-invast** [comment]
This is my work account ([personal](https://github.com/franciscop)) but sure, I'll do juts that. I found the repo through literally googling for `npm is internal link` :smiley:

I had some ideas (as shown above), but wanted to see if I was missing anything so decided to search for 3rd parties solutions. Checking for `//` as well came from SO.

BTW, would you be happy with this syntax instead? I find it a bit cleaner but that'd be up to you since it's your repo after all:

```js
import isInternalLink from 'is-internal-link';
```

**Comment by franciscop-invast** [comment]
(or both syntaxes for importing it to avoid having to bump a major version it just for that)

**Comment by muhajirdev** [comment]
Sure sure, Let's export both.

**Comment by muhajirdev** [comment]
Hey, new version published

And can now import like this
```javascript
import isInternalLink from 'is-internal-link';
```
